version: '3.8'

services:
  postgres:
    container_name: cooperspostgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: coopers_db
      POSTGRES_USER: coopers_user
      POSTGRES_PASSWORD: coopers_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coopersnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coopers_user -d coopers_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: coopersbackend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: cooperspostgres
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: coopers_user
      TYPEORM_PASSWORD: coopers_password
      TYPEORM_DATABASE: coopers_db
      JWT_SECRET: d19f823533b6848c70fd7733bbded54af5c93a4c5f13a6f14438b61f9f311237e2998ae7d270dd6bc6c5abc9d1b6a11c3d0baf0078e6a98731c25eeafbed6bc1
      JWT_REFRESH_SECRET: 29a44aadaf19d8a82110a00668b20097bd5a397cf5ed206a662d6ff3c9d08c7e7dcada1c44bd14b54ed945827eb068e825955a5caad981a20938eae99ce87e86
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coopersnetwork

  frontend:
    container_name: coopersfrontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXTAUTH_SECRET: d19f823533b6848c70fd7733bbded54af5c93a4c5f13a6f14438b61f9f311237e2998ae7d270dd6bc6c5abc9d1b6a11c3d0baf0078e6a98731c25eeafbed6bc1
      NEXTAUTH_URL: http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - coopersnetwork

volumes:
  postgres_data: 

networks:
  coopersnetwork:
    name: coopersnetwork
    driver: bridge 


